research_query:
  description: >
    Research the knowledge base to find relevant information to answer the following question: "{user_question}"
    Use the knowledge files available to find the most accurate and helpful information. If the knowledge base
    doesn't contain specific information to answer the question, clearly state that limitation and provide
    general best practices related to the topic.
  expected_output: >
    Accurate findings from the knowledge base answering '{user_question}', including relevant details or steps.
    If no specific answer exists, note the limitation and provide relevant best practices.
  agent: knowledge_researcher

formulate_answer:
  description: >
    Using the research, provide a clear, concise answer to '{user_question}' as an experienced DevOps engineer. 
    Include relevant technical details and practical steps or best practices, keeping it accessible.
  expected_output: >
    A clear, concise, technically accurate answer to '{user_question}', reflecting DevOps best practices with relevant details or steps from the knowledge base, presented in an accessible manner.
  agent: devops_assistant
